Make provider explicity on service resource
Without this change, the consul service fails to start or reload and puppet
outputs the following errors:

Debug: Exec[consul-systemd-reload](provider=posix): Executing 'systemctl daemon-reload'
Debug: Executing: 'systemctl daemon-reload'
Notice: /Stage[main]/Consul::Config/Exec[consul-systemd-reload]: Triggered 'refresh' from 1 events
Debug: /Stage[main]/Consul::Config/Exec[consul-systemd-reload]: The container Class[Consul::Config] will propagate my refresh event
Debug: Class[Consul::Config]: The container Stage[main] will propagate my refresh event
Info: Class[Consul::Config]: Scheduling refresh of Class[Consul::Run_service]
Info: Class[Consul::Run_service]: Scheduling refresh of Service[consul]
Debug: Executing: 'systemctl is-active consul'
Debug: Service[consul](provider=debian): Could not find consul in /etc/init.d
Debug: Service[consul](provider=debian): Could not find consul.sh in /etc/init.d
Error: Could not find init script for 'consul'
Error: /Stage[main]/Consul::Run_service/Service[consul]/ensure: change from stopped to running failed: Could not find init script for 'consul'
Debug: Executing: 'systemctl is-active consul'
Debug: /Stage[main]/Consul::Run_service/Service[consul]: Skipping restart; service is not running
Notice: /Stage[main]/Consul::Run_service/Service[consul]: Triggered 'refresh' from 1 events
Debug: /Stage[main]/Consul::Run_service/Service[consul]: The container Class[Consul::Run_service] will propagate my refresh event
Debug: Class[Consul::Run_service]: Resource is being skipped, unscheduling all events
Info: Class[Consul::Run_service]: Unscheduling all events on Class[Consul::Run_service]
Debug: Class[Consul::Reload_service]: Resource is being skipped, unscheduling all events
Info: Class[Consul::Reload_service]: Unscheduling all events on Class[Consul::Reload_service]
Warning: /Stage[main]/Consul::Reload_service/Exec[reload consul service]: Skipping because of failed dependencies
Warning: /Stage[main]/Consul/Anchor[consul_last]: Skipping because of failed dependencies
Notice: /Stage[main]/Consul::Reload_service/Exec[reload consul service]: Dependency Service[consul] has failures: true
Debug: /Stage[main]/Consul::Reload_service/Exec[reload consul service]: Resource is being skipped, unscheduling all events
Debug: Class[Consul::Reload_service]: Resource is being skipped, unscheduling all events

I suspect this is a bug in Puppet on Ubuntu 15.10, due to the switch from
upstart to systemd that commenced in 15.04.  Given Puppetlabs haven't even
released packages for 15.10 yet (and that appears to be waiting for 15.10
test infrastructure to be ready), this isn't altogether unexpected.

As such, this is being implemented as a patch against this module at least
until Puppetlabs release Ubuntu 15.10 (or later) packages.